name: suds
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=39.0.1=py39h9ce1e76_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.1.55=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.1.55=0
  - cuda-nsight-compute=12.1.0=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.1.55=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.1.55=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.1.55=0
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.1.55=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-visual-tools=11.6.1=0
  - ffmpeg=4.3=hf484d3e_0
  - flit-core=3.8.0=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gds-tools=1.6.0.25=0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py39h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.6.0.25=0
  - libcufile-dev=1.6.0.25=0
  - libcurand=10.3.2.56=0
  - libcurand-dev=10.3.2.56=0
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - nsight-compute=2023.1.0.15=0
  - numpy=1.23.5=py39h14f4228_0
  - numpy-base=1.23.5=py39h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - pillow=9.4.0=py39h6a678d5_0
  - pip=23.0.1=py39h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.16=h7a1cb2a_2
  - pytorch=1.13.1=py3.9_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py39h06a4308_1
  - setuptools=65.6.3=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.1=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - torchvision=0.14.1=py39_cu116
  - typing_extensions=4.4.0=py39h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.14=py39h06a4308_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==1.4.0
      - aiofiles==22.1.0
      - aiosqlite==0.18.0
      - anyio==3.6.2
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - attrs==22.2.0
      - av==10.0.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.0
      - bidict==0.22.1
      - bleach==6.0.0
      - cachetools==5.3.0
      - click==8.1.3
      - comm==0.1.3
      - configargparse==1.5.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - debugpy==1.6.6
      - decorator==5.1.1
      - defusedxml==0.7.1
      - descartes==1.1.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.14.1
      - executing==1.2.0
      - fastjsonschema==2.16.3
      - filelock==3.10.3
      - fire==0.5.0
      - fonttools==4.39.2
      - fqdn==1.5.1
      - frozendict==2.3.6
      - gdown==4.6.4
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-auth==2.16.3
      - google-auth-oauthlib==0.4.6
      - grpcio==1.51.3
      - h5py==3.8.0
      - huggingface-hub==0.13.3
      - imageio==2.26.1
      - importlib-metadata==6.1.0
      - importlib-resources==5.12.0
      - ipykernel==6.22.0
      - ipython==8.11.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.5
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - json5==0.9.11
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.1.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-server==2.5.0
      - jupyter-server-fileid==0.8.0
      - jupyter-server-terminals==0.4.4
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.3
      - jupyterlab==3.6.2
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.21.0
      - jupyterlab-widgets==3.0.6
      - kiwisolver==1.4.4
      - lazy-loader==0.2
      - lpips==0.1.4
      - markdown==3.4.3
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mediapy==1.1.6
      - mistune==2.0.5
      - msgpack==1.0.5
      - msgpack-numpy==0.4.8
      - nbclassic==0.5.3
      - nbclient==0.7.2
      - nbconvert==7.2.10
      - nbformat==5.8.0
      - nerfacc==0.3.5
      - nest-asyncio==1.5.6
      - networkx==3.0
      - ninja==1.11.1
      - notebook==6.5.3
      - notebook-shim==0.2.2
      - nuscenes-devkit==1.1.9
      - oauthlib==3.2.2
      - opencv-python==4.6.0.66
      - packaging==23.0
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==3.1.1
      - plotly==5.13.1
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.38
      - protobuf==3.20.3
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==11.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycocotools==2.0.6
      - pyequilib==0.5.6
      - pygments==2.14.0
      - pymeshlab==2022.2.post3
      - pyngrok==5.2.1
      - pyparsing==3.0.9
      - pyquaternion==0.9.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-engineio==4.4.0
      - python-json-logger==2.0.7
      - python-socketio==5.8.0
      - pytz==2022.7.1
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==25.0.2
      - qtconsole==5.4.1
      - qtpy==2.3.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.3.2
      - rsa==4.9
      - scikit-image==0.20.0
      - scikit-learn==1.2.2
      - scipy==1.9.1
      - send2trash==1.8.0
      - sentry-sdk==1.17.0
      - setproctitle==1.3.2
      - shapely==2.0.1
      - shtab==1.5.8
      - smart-open==6.3.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4
      - stack-data==0.6.2
      - suds-cuda==0.0.0
      - tenacity==8.2.2
      - tensorboard==2.9.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.2.0
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tifffile==2023.3.21
      - timm==0.6.13
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torch-fidelity==0.3.0
      - torchmetrics==0.11.4
      - torchtyping==0.1.4
      - tornado==6.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - typeguard==3.0.2
      - tyro==0.4.2
      - u-msgpack-python==2.7.2
      - uri-template==1.2.0
      - wandb==0.14.0
      - wcwidth==0.2.6
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.6
      - xatlas==0.0.7
      - y-py==0.5.9
      - ypy-websocket==0.8.2
      - zipp==3.15.0
      - git+https://github.com/hturki/nerfstudio.git@ht/suds
      - git+https://github.com/hturki/tiny-cuda-nn.git@ht/res-grid#subdirectory=bindings/torch
